In [58]:
#Önceki üç harfi bağlam alan veri setini kur (X: 3 harf indeksi, Y: sıradaki harf).
#Embedding tablosunu (27x2) oluştur, indeksleme ile embedding'leri çek. 
#libraries & data 
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

words = open('names.txt', 'r').read().splitlines()

In [84]:
#character mappings; i to s or vice versa
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [85]:
block_size = 3 # context length: how many characters do we take to predict the next one?
X, Y = [], []
for w in words:
  
  context = [0] * block_size
  for ch in w + '.':
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    context = context[1:] + [ix] # crop and append   
X = torch.tensor(X)
Y = torch.tensor(Y)

In [86]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([228146, 3]), torch.int64, torch.Size([228146]), torch.int64)

In [87]:
sum(len(w) + 1 for w in words)

228146

In [88]:
#27x2 lookuptable
C = torch.randn(27,2)
C.shape
X[:2]

tensor([[0, 0, 0],
        [0, 0, 5]])

In [89]:
emb = C[X]
emb.shape

torch.Size([228146, 3, 2])

In [107]:
X[11]

tensor([22,  9,  1])

In [106]:
C[X][11]

tensor([[-1.4717, -1.6152],
        [ 0.3679, -0.2406],
        [ 1.1939, -0.3497]])

In [104]:
C[22],C[9], C[1]

(tensor([-1.4717, -1.6152]),
 tensor([ 0.3679, -0.2406]),
 tensor([ 1.1939, -0.3497]))